version: "3.3"
   
services:
  vpn:
    #image: pia_vpn:latest
    image: xanderu/pia_vpn:0.0.1
    cap_add:
      - net_admin
    dns:
     - 8.8.8.8
     - 8.8.4.4
    ports:
      - "12345:51413"               #transmission
      - "12345:51413/udp"           #transmission
      - "9091:9091"                 #transmission Web
      - "8989:8989"                 #sonar Web
      - "7878:7878"                 #radarr Web
      - "8686:8686"                 #lidarr Web
      - "9117:9117"                 #jackett Web
      - "3579:3579"                 #ombi Web
      - "9000:9000"                 #portainer Web
      - "5299:5299"                 #Lazylibrarian
    environment:
      USERNAME: "${PIAUSERNAME}"
      PASSWORD: "${PIAPASSWORD}"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    
  transmission:
    image: linuxserver/transmission
    depends_on:
      - vpn
    environment:
      TZ: ${ZONE}
      PGID: 0
      PUID: 0
      TRANSMISSION_WEB_HOME: "/kettu/"
    network_mode: "service:vpn"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - transmission:/config
      - downloads:/downloads
      
  sonarr:
    image: linuxserver/sonarr:latest
    depends_on:
      - vpn
    restart: always
    network_mode: "service:vpn"
    environment:
      TZ: ${TZONE}
      PGID: 0
      PUID: 0
    volumes:
      - sonarr:/config
      - downloads:/downloads
      - tv:/tv
    
  radarr:
    image: linuxserver/radarr
    depends_on:
      - vpn
    restart: always
    network_mode: "service:vpn"
    environment:
      TZ: ${TZONE}
      PGID: 0
      PUID: 0
    volumes:
      - radarr:/config
      - downloads:/downloads
      - movies:/movies
      
  lidarr:
    image: linuxserver/lidarr
    depends_on:
      - vpn
    restart: always
    network_mode: "service:vpn"
    environment:
      TZ: ${TZONE}
      PGID: 0
      PUID: 0
    volumes:
      - lidarr:/config
      - downloads:/downloads
      - music:/music

  jackett:
    image: linuxserver/jackett
    depends_on:
      - vpn
    restart: always
    network_mode: "service:vpn"
    environment:
      TZ: ${TZONE}
      PGID: 1000
      PUID: 1000
    volumes:
      - jackett:/config
      - downloads:/downloads

  ombi:
    image: linuxserver/ombi
    depends_on:
      - vpn
    restart: always
    network_mode: "service:vpn"
    environment:
      TZ: ${TZONE}
      PGID: 0
      PUID: 0
    volumes:
      - ombi:/config

  portainer:
    image: portainer/portainer-ce
    restart: always
    network_mode: "service:vpn"
    environment:
      TZ: ${TZONE}
      PGID: 0
      PUID: 0
    volumes:
      - type: bind 
        source: //var/run/docker.sock
        target: //var/run/docker.sock

  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    environment:
      TZ: ${TZONE}
      PGID: 1000
      PUID: 1000
      DOCKER_MODS: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: always
    volumes:
      - lazylibrarian:/config
      - downloads:/downloads
      - books:/books
      
volumes:
    downloads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${SMBNETADDRE}/downloads
        
    tv:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${SMBNETADDRE}/TV
        
    books:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${SMBNETADDRE}/Books
        
    movies:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${SMBNETADDRE}/Movies
        
    music:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${SMBNETADDRE}/Music
        
    transmission:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/transmission
        
    jackett:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: ${LOCALADDRES}/docker/jackett

    sonarr:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/sonarr

    radarr:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/radarr
                
    lidarr:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/lidarr
                    
    ombi:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/ombi

    jellyfinconfig:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/jellyfin/config

    jellyfincache:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${LOCALADDRES}/docker/jellyfin/cache

    lazylibrarian:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: ${LOCALADDRES}/docker/lazylibrarian
